apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-universal-pipeline
spec:
  serviceAccountName: jenkins-build-sa  # create in EKS and bind required IAM role
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:4.10-3
      args:
        - ${computer.jnlpmac}
        - ${computer.name}
    - name: sonar
      image: sonarsource/sonar-scanner-cli:4.7.0
      resources:
        limits:
          cpu: "1"
          memory: "1Gi"
    - name: checkov
      image: bridgecrew/checkov:2.0.607
      resources:
        limits:
          cpu: "1"
          memory: "1Gi"
    - name: sbom
      image: anchore/syft:1.12.0
      resources:
        limits:
          cpu: "0.5"
          memory: "512Mi"
    - name: trivy
      image: aquasec/trivy:0.45.0
      resources:
        limits:
          cpu: "0.5"
          memory: "512Mi"
    - name: docker
      image: docker:24-dind
      securityContext:
        privileged: true
      resources:
        limits:
          cpu: "2"
          memory: "2Gi"
    - name: curl
      image: curlimages/curl:7.88.1
  restartPolicy: Never
