apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-checkov
spec:
  serviceAccountName: jenkins-build-sa
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:4.10-3
      args:
        - ${computer.jnlpmac}
        - ${computer.name}
    - name: checkov
      image: bridgecrew/checkov:2.0.607
      resources:
        limits:
          cpu: "1"
          memory: "1Gi"
  restartPolicy: Never
