apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-docker
spec:
  serviceAccountName: jenkins-build-sa
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:4.10-3
      args:
        - ${computer.jnlpmac}
        - ${computer.name}
    - name: docker
      image: docker:24-dind
      securityContext:
        privileged: true
      resources:
        limits:
          cpu: "2"
          memory: "2Gi"
  restartPolicy: Never
