apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-sbom
spec:
  serviceAccountName: jenkins-build-sa
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:4.10-3
      args:
        - ${computer.jnlpmac}
        - ${computer.name}
    - name: sbom
      image: anchore/syft:1.12.0
      resources:
        limits:
          cpu: "0.5"
          memory: "512Mi"
  restartPolicy: Never
